# Generated by Django 4.0.5 on 2022-07-06 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
                ('discription', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='./image')),
                ('content', models.TextField(blank=True, null=True)),
                ('totalMarks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('allowedAttempt', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('totalMarks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timeLimit', models.IntegerField(default=20)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='quizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('choosenOptions', models.TextField(blank=True, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.quiz')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('maxMarks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allOptions', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completionPercentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currMarks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=50, null=True)),
                ('Lname', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor')], default='Student', max_length=10)),
                ('coursesEnrolled', models.ManyToManyField(blank=True, related_name='Courses', to='lms.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('Instructor', 'code'), name='unique_course'),
        ),
    ]
