# Generated by Django 4.0.5 on 2022-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses_enrolled',
            field=models.ManyToManyField(blank=True, related_name='Courses', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_courses',
            field=models.ManyToManyField(blank=True, related_name='CreatedCourses', to='lms.course'),
        ),
    ]
