# Generated by Django 4.0.5 on 2022-06-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0003_alter_profile_fname_alter_profile_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='Instructor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Checked', 'Checked')], default='Not Submitted', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
