# Generated by Django 4.0.5 on 2022-06-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_remove_assignment_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='totalMarks',
        ),
        migrations.AddField(
            model_name='course',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
