# Generated by Django 4.0.5 on 2022-06-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_rename_courses_enrolled_profile_coursesenrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timeLimit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
